formattingCodePrefix = "ยง"
signFormattingEnabled = true
bookFormattingEnabled = true
anvilFormattingEnabled = true
signEditingEnabled = true
signClickThroughEnabled = true
itemFrameClickThroughEnabled = true
additionalClickThroughIdentifiers = ["create:placard"]
