# Controls blob caching (Reduces network usage and loading time), Valid options: "disabled", "memory", "disk"
blob-cache: disk
# If enabled, starts the resource pack HTTP server and enables resource pack translation
translate-resource-packs: true
# Resource pack HTTP server address
resource-pack-host: 127.0.0.1
# Resource pack HTTP server port (0 = random available port)
resource-pack-port: 0
# Resource pack URL which the clients will use to download the resource pack (empty = auto)
resource-pack-url: ''
# Controls resource pack caching (Reduces network usage and loading time), Valid options: "disabled", "memory", "disk"
pack-cache: disk
